from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Directories for data
DATA_DIR = PROJECT_ROOT / "data"
RAW_BUCKET = DATA_DIR / "raw"
RAW_RETRIEVAL_LOG = RAW_BUCKET / "retrieval_log.csv"
RAW_THROUGHPUT_BUCKET = RAW_BUCKET / "throughput"
RAW_GEOSPATIAL_BUCKET = RAW_BUCKET / "geospatial"
RAW_TM_GEOSPATIAL_BUCKET = RAW_GEOSPATIAL_BUCKET / "transmountain"
VALIDATED_RAW_BUCKET = DATA_DIR / "validated"
VALIDATED_THROUGHPUT_BUCKET = VALIDATED_RAW_BUCKET / "throughput"
VALIDATED_PRODUCTION_BUCKET = VALIDATED_RAW_BUCKET / "production"
VALIDATED_RAIL_BUCKET = VALIDATED_RAW_BUCKET / "rail"
QUARANTINE_BUCKET = DATA_DIR / "quarantine"
QUARANTINE_THROUGHPUT_BUCKET = QUARANTINE_BUCKET / "throughput"
QUARANTINE_PRODUCTION_BUCKET = QUARANTINE_BUCKET / "production"
QUARANTINE_RAIL_BUCKET = QUARANTINE_BUCKET / "rail"
VALIDATION_REPORTS_BUCKET = DATA_DIR / "validation"
VALIDATION_THROUGHPUT_REPORTS_BUCKET = VALIDATION_REPORTS_BUCKET / "throughput"
VALIDATION_PRODUCTION_REPORTS_BUCKET = VALIDATION_REPORTS_BUCKET / "production"
VALIDATION_RAIL_REPORTS_BUCKET = VALIDATION_REPORTS_BUCKET / "rail"
TRANSFORMED_BUCKET = DATA_DIR / "transformed"

# Ouput stages
THROUGHPUT_STAGE_1 = TRANSFORMED_BUCKET / "throughput_stage_1"

# Final stage-2 tables consumed by downstream analysis.
THROUGHPUT_STAGE_2_FLOW = TRANSFORMED_BUCKET / "pipeline_flow.csv"
THROUGHPUT_STAGE_2_CAPACITY = TRANSFORMED_BUCKET / "pipeline_capacity.csv"

# Constants between files
CUBIC_M_TO_BARRELS = 6.2898
